jobs:
   stage: deploy
   variables:
        GIT_STRATEGY: none
   script:
   - pwd
   - cd /home/shopify/public_html/delish-shopify-vue
   - git config user.name "gorakh.shrestha"
   - git config user.email "gorakh.shrestha@ebpearls.com"
   - git pull origin master
   only:
    - master
